We implemented the division-based Euklid algorithm

In [1]:
function OwnGcd(a,b)
    while b ≠ 0
        t = b
        b = a %b
        a = t
    end
    return abs(a)
end

OwnGcd (generic function with 1 method)

To test the code we genreater random integers and compare our fdunction to the build in one.

In [3]:
for _ in 1:10
    a = rand(Int16)
    b = rand(Int16)
    @assert OwnGcd(a,b) == gcd(a,b)
end

In [4]:
function findPeriod(a,N)
    x = 1
    result = a % N
    while result != 1
        result = (result * a) % N
        x += 1
    end
    return x
end

findPeriod (generic function with 1 method)

In [5]:
function findPrimeFactors(N)
    while true
    a = rand(1:N-1)
    d = OwnGcd(a, N)
    if d != 1
        return d
    end
    r = findPeriod(a, N)
    if r % 2 == 1
        continue
    end
    a_r_half = powermod(a, r ÷ 2, N)
    if a_r_half == N - 1
        continue
    end
    return OwnGcd(a_r_half + 1, N), OwnGcd(a_r_half - 1, N)
end
end

findPrimeFactors (generic function with 1 method)

In [145]:
function inverse(a,n)
    t = 0; r=n
    t_new = 1; r_new =a
    while r_new ≠ 0

        qt = ÷(r,r_new)
        t, t_new = (t_new, t- qt*t_new)
        r, r_new = (r_new, r- qt*r_new)

    end
    @assert !(r>1)
    return t*(1+n*(t<0))
end

inverse (generic function with 1 method)

In [146]:
ϕ(p,q) = (p-1)*(q-1)

ϕ (generic function with 1 method)

In [147]:
N = 71219839
e = 4187899

4187899

In [148]:
@show p, q = findPrimeFactors(N)
@assert p*q == N

(p, q) = findPrimeFactors(N) = (7649, 9311)


In [149]:
d =inverse(e,ϕ(p,q))

6567859

Thus the decryption Key is d = 6567859, and p = 7649, q = 9311

**2.**

In [194]:
key = Dict([(Char(97 +i  ),i) for i in 0:25])

Dict{Char, Int64} with 26 entries:
  'n' => 13
  'f' => 5
  'w' => 22
  'd' => 3
  'e' => 4
  'o' => 14
  'h' => 7
  'j' => 9
  'i' => 8
  'k' => 10
  'r' => 17
  's' => 18
  't' => 19
  'q' => 16
  'y' => 24
  'a' => 0
  'c' => 2
  'p' => 15
  'm' => 12
  ⋮   => ⋮

In [225]:
function getEncodedMassage(string,keys)
    encodedMessage = 0
    for (i,char) in enumerate(reverse(string))
        encodedMessage += key[char]*26^(i-1)
    end
    return encodedMessage
end
function getDecodedMassage(int, keys)
    message = ""
    while int > 0
         message = keys[(int % 26)] * message
        int ÷= 26
    end
    return message
end

getDecodedMassage (generic function with 1 method)

To test the encoder I use the example of the sheet:

In [226]:
getEncodedMassage("hallo",keys)

3206568

I can now encode the string "bwtlqv":

In [227]:
secretMsg = getEncodedMassage("bwtlqv",keys)

22276665

I can decrypt the massage using the decryption Key d and N:

In [228]:
m = powermod(secretMsg, d,N)

203179

To get back the secret massage I have to reverse the Dict:

In [229]:
rkeys = Dict(v => k for (k,v) in key)

Dict{Int64, Char} with 26 entries:
  5  => 'f'
  16 => 'q'
  20 => 'u'
  12 => 'm'
  24 => 'y'
  8  => 'i'
  17 => 'r'
  23 => 'x'
  19 => 't'
  22 => 'w'
  0  => 'a'
  6  => 'g'
  1  => 'b'
  11 => 'l'
  9  => 'j'
  14 => 'o'
  3  => 'd'
  7  => 'h'
  25 => 'z'
  ⋮  => ⋮

Finally I can decode the decrypted massage

In [232]:
getDecodedMassage(m,rkeys)

"loop"

The secret massage is thus "loop"